# Generated by Django 5.1.4 on 2024-12-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
    ]
